spring.application.name=banking-management
spring.datasource.url=jdbc:mysql://localhost:3306/banking_db
spring.datasource.username=root
spring.datasource.password=Sai@14042005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
